name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest ruff httpx

      # Keep lint strict but focused on real errors (F,E9)
      - name: Lint (ruff)
        run: ruff check . --select F,E9

      - name: Run tests
        run: python -m pytest -q

      - name: Train smoke (produces artifacts)
        run: python -m src.train --out_dir models

      - name: Upload training artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: models/*