name: Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      REPO_RAW: ${{ github.repository }}
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Train deterministically
        run: |
          python -m src.train --out_dir models --kind ridge
          cat models/metrics.json

      - name: Normalize image name (lowercase for GHCR)
        id: name
        run: |
          echo "image=ghcr.io/$(echo "$REPO_RAW" | tr '[:upper:]' '[:lower:]'):${TAG}" >> $GITHUB_OUTPUT

      - name: Build image
        run: docker build --build-arg MODEL_KIND=ridge -t ${{ steps.name.outputs.image }} .

      - name: Smoke test container (retry for readiness)
        run: |
          cid=$(docker run -d -p 8000:8000 ${{ steps.name.outputs.image }})
          echo "Container: $cid"
          for i in {1..15}; do
            if curl -sSf http://127.0.0.1:8000/health > health.json; then
              break
            fi
            echo "Waiting for API... ($i)"; sleep 2
          done
          cat health.json
          curl -sSf -X POST http://127.0.0.1:8000/predict \
            -H 'Content-Type: application/json' \
            -d '{"age":0.02,"sex":-0.044,"bmi":0.06,"bp":-0.03,"s1":-0.02,"s2":0.03,"s3":-0.02,"s4":0.02,"s5":0.02,"s6":-0.001}' \
            | tee predict.json
          docker rm -f $cid

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image (patch & minor tags)
        run: |
          docker push ${{ steps.name.outputs.image }}
          # also push minor tag v0.1
          MINOR=${TAG%.*}
          docker tag ${{ steps.name.outputs.image }} ghcr.io/$(echo "$REPO_RAW" | tr '[:upper:]' '[:lower:]'):${MINOR}
          docker push ghcr.io/$(echo "$REPO_RAW" | tr '[:upper:]' '[:lower:]'):${MINOR}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          body: |
            Automated release for ${{ env.TAG }}.
            See CHANGELOG.md for details. Metrics attached.
          files: |
            models/metrics.json
            CHANGELOG.md