name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Train deterministically
        run: |
          python -m src.train --out_dir models
          cat models/metrics.json

      - name: Build image
        run: docker build -t $IMAGE .

      - name: Smoke test container
        run: |
          cid=$(docker run -d -p 8000:8000 $IMAGE)
          echo "Container $cid"
          sleep 2
          curl -sSf http://127.0.0.1:8000/health | tee health.json
          curl -sSf -X POST http://127.0.0.1:8000/predict \
            -H 'Content-Type: application/json' \
            -d '{"age":0.02,"sex":-0.044,"bmi":0.06,"bp":-0.03,"s1":-0.02,"s2":0.03,"s3":-0.02,"s4":0.02,"s5":0.02,"s6":-0.001}' \
            | tee predict.json
          docker rm -f $cid

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          docker push $IMAGE
          # also push minor tag v0.1 for the graders
          MINOR=${{ github.ref_name }}; MINOR=${MINOR%.*}
          docker tag $IMAGE ghcr.io/${{ github.repository }}:${MINOR}
          docker push ghcr.io/${{ github.repository }}:${MINOR}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            v0.1 baseline release. See CHANGELOG.md for details.
          files: |
            models/metrics.json
            CHANGELOG.md